### ISSUE TITLE
Advanced Deployments Documentation

### ISSUE THREAD

**Issue by Kukks** [btcpayserver/btcpayserver-doc#199]
* How to deploy BtcPay, NBXplorer & Postgres through docker and integrate with existing ln and btc nodes.

Requested a few times and would be easier than building from source for some (e.g @aantonop's recent setup issues, he has restricted access on a user on linux causing js/css bundles to fail in an unexpected way, docker for the essentials services would make this a million times easier)

**Comment by pavlenex** [comment]
We now have [ManualDeploymentExtended.md](https://github.com/btcpayserver/btcpayserver-doc/blob/master/ManualDeploymentExtended.md), so I guess this one is done or is there something more you had in mind @Kukks?

**Comment by Kukks** [comment]
Nah I have more in mind, such as mixing and matching a docker install with
existing services. I'll try and do it on the plane

**Comment by pavlenex** [comment]
It looks like @Kukks's plane never took off 😄

**Comment by pavlenex** [comment]
@Kukks travels through time and universe.

**Comment by Kukks** [comment]
ok ok fuck

**Comment by Kukks** [comment]
## Deploying BTCPay Server using Docker alongside your existing Bitcoin node

* run setup as described in btcpayserver-docker up until `. ./btcpay-setup.sh -i`
* create `bitcoin.custom.yml` in the `docker-compose-generator/docker-fragments/` folder.
```yml
version: "3"

services:
  btcpayserver:
      environment:
        BTCPAY_CHAINS: "btc"
        BTCPAY_BTCEXPLORERURL: http://nbxplorer:32838/
  nbxplorer:
      environment:
        NBXPLORER_CHAINS: "btc"
        NBXPLORER_BTCRPCURL: http://host.docker.internal:43782/
        NBXPLORER_BTCNODEENDPOINT: host.docker.internal:39388
      volumes:
        - "localBitcoinfolder:/root/.bitcoin"
```
* Replace: `43782` with your bitcoin node's configured RPC port
* Replace: `39388` with your bitcoin node's configured p2p port
* Replace `localBitcoinfolder` with the path to your bitcoin data folder
If you are running on linux, due to [a limitation of docker](https://github.com/docker/for-linux/issues/264), you will also need to do the following:
* Run `ip route | grep docker0 | awk '{print $9}'`
  * Add the following at the end of the `bitcoin.custom.yml` file, replacing `$DOCKER_HOST_IP` with the result of the previous command. 
```yml
      extra_hosts:
        - "host.docker.internal:$DOCKER_HOST_IP"
```

* Run `BTCPAYGEN_EXCLUDE_FRAGMENTS="bitcoin"`
* Run `BTCPAYGEN_ADDITIONAL_FRAGMENTS="$BTCPAYGEN_ADDITIONAL_FRAGMENTS"`
* Run `. ./btcpay-setup.sh -i`
