### ISSUE TITLE
Add documentation to integrate custom apps to docker behind nginx

### ISSUE THREAD

**Issue by Kukks** [btcpayserver/btcpayserver-doc#762]
When you  add an application to the docker plugin system, you need to make nginx proxy to it
```
version: "3"

services:
  nginx-gen:
    environment:
      ADDITIONAL_NGINX_CONFIG: |
        server { 
          server_name xyz.mydomain.com; 
          proxy_pass http://YOURDOCKERCONTAINER:PORT;
        }
```

**Comment by NicolasDorier** [comment]
no you don't

**Comment by NicolasDorier** [comment]
If you want domain routing, you don't need to change the nginx at all.

**Comment by Kukks** [comment]
> If you want domain routing, you don't need to change the nginx at all.

No but for other scenarios you do, for example wanting to do a redirection or other stuff

**Comment by NicolasDorier** [comment]
I see, but your example here show domain routing.

**Comment by Zaxounette** [comment]
Kukks & Nicolas, what's the status on this ?

Still to be added to the docs, or not ?
Where ? docker.md ?

**Comment by dennisreimann** [comment]
imho we shopuld separate out the FAQs from the Docker/README.md and add them as a separate section in the Deployment FAQs … that's where I'd expect to find them from a users perspective and it would be consistent with the rest of the docs.

We should then put this as an additional point there:

````markdown
# How to add a custom plugin to the Docker deployment

When you add an application to the docker plugin system, you need to make nginx proxy to it:
````

```yml
version: "3"

services:
  nginx-gen:
    environment:
      ADDITIONAL_NGINX_CONFIG: |
        location /my-plugin/ {
          proxy_pass http://YOURDOCKERCONTAINER:PORT;
          # additional config like proxy headers go here …
        }
```

```markdown
You can then use the `BTCPAYGEN_ADDITIONAL_FRAGMENTS` environment variable to add your custom plugin fragment.
See [this FAQ entry](#how-can-i-customize-the-generated-docker-compose-file) for details.
```

None of the services from the docker repo (e.g. ThunderHub or RTL) use this method of integrating – I think we should also clarify when to use `ADDITIONAL_NGINX_CONFIG` instead of `BTCPAY_EXTERNALSERVICES`.
